package com.madanala.tern.ui

import androidx.lifecycle.ViewModelProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.madanala.tern.TernParaglidingActivity
import com.madanala.tern.redux.MapAction
import com.madanala.tern.redux.MapStore
import com.madanala.tern.utils.CacheManager
import com.madanala.tern.utils.MapTestHelper
import com.madanala.tern.utils.MapVisualTest
import com.madanala.tern.utils.PerformanceDebugger
import com.madanala.tern.utils.CountryUtils
import org.junit.Test
import org.junit.runner.RunWith
import org.osmdroid.util.GeoPoint

@RunWith(AndroidJUnit4::class)
class MapMemoryStressTest : MapVisualTest() {

    @Test
    fun testAlpineHighDensityMemoryStress() {
        scenario("Baseline - Idle Map") {
            val activity = composeTestRule.activity as TernParaglidingActivity
            val store = ViewModelProvider(activity)[MapStore::class.java]
            
            given("The map is initialized and idle") {
                 CacheManager.initialize(activity.applicationContext)
                 MapTestHelper.grantLocationPermissions()
                 composeTestRule.waitForIdle()
                 PerformanceDebugger.logHeapUsage("BASELINE_IDLE")
            }
        }

        scenario("Stress Test - Alpine High Density PG Spots") {
            val activity = composeTestRule.activity as TernParaglidingActivity
            val store = ViewModelProvider(activity)[MapStore::class.java]
            
            given("The map is centered on Chamonix, French Alps (High PG Spot Density)") {
                 // Chamonix: 45.9237, 6.8694
                 CountryUtils.setTestCountryCode("FR")
                 
                 // Use Redux as ONLY Source of Truth for camera
                 store.dispatch(MapAction.UpdateCenter(GeoPoint(45.9237, 6.8694)))
                 store.dispatch(MapAction.UpdateZoom(12.0))
                 
                 composeTestRule.waitForIdle()
                 // [CLOSED-LOOP] Verify the move actually happened
                 assertMapLocation(45.9237, 6.8694)
                 
                 // Wait for debounce in BaseOverlayManager (300ms) to fire performMapMove
                 Thread.sleep(500)
                 
                 // Wait for PG spots to load and render initially
                 // [STRICT VERIFICATION] Remove try-catch to expose failures
                 waitForPGSpots(minCount = 5, timeoutMillis = 20000)
                 PerformanceDebugger.logHeapUsage("STRESS_START_AFTER_LOAD")
            }

            `when`("The user performs sustained rapid panning for 10 seconds") {
                val startLat = 45.9237
                val startLon = 6.8694
                val endLat = 46.0
                val endLon = 7.0
                
                // Perform multiple rapid pans to churn memory via ViewToBitmap
                repeat(5) {
                    MapTestHelper.swipeMap(
                        activity = activity,
                        startLat = startLat,
                        startLon = startLon,
                        endLat = endLat,
                        endLon = endLon,
                        steps = 20
                    )
                    composeTestRule.waitForIdle()
                    
                    MapTestHelper.swipeMap(
                        activity = activity,
                        startLat = endLat,
                        startLon = endLon,
                        endLat = startLat,
                        endLon = startLon,
                        steps = 20
                    )
                    composeTestRule.waitForIdle()
                }
            }

            then("The system should maintain heap stability", takeScreenshot = true) {
                // Stop interaction and let system settle
                Thread.sleep(2000)
                
                // Force GC to see if memory returns to baseline (leak detection)
                System.gc()
                Thread.sleep(1000)
                
                PerformanceDebugger.logHeapUsage("STRESS_RECOVERY_END")
            }
            
            and("The performance scorecard should show memory churn levels") {
                // Scorecard is automatically generated by ReportGenerator at end of scenario
            }
        }
    }
}
